In [ ]:
from sklearn.datasets import fetch_openml
#load mice protein dataset from OpenML
mice = fetch_openml(name='miceprotein', version=4, as_frame=True)
list(mice.frame.columns)
#print(mice.details)
#mice.frame.describe()


# Import required libraries
import numpy as np
import sklearn
from sklearn.neural_network import MLPClassifier


# Import model to divide data into training and testing sets
from sklearn.model_selection import train_test_split


target_column = ['class']
#derive the list of predictor column id's
predictors = list(set(list(mice.frame.columns))-set(target_column))
#standardize the predictors by diividing by the maximum
mice.frame[predictors] = mice.frame[predictors]/mice.frame[predictors].max()
#provide summary statistics for the dataframe
mice.frame.describe().transpose()

#Get rid of any rown with NA's
mice.frame = mice.frame.dropna()

#the input data
X = mice.frame[predictors].values
#the output data
y = mice.frame[target_column].values

#we encode target classes from strings to numbers as neural networks cannot require all numerical inputs and outputs
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#divide data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train.shape); print(X_test.shape)

from sklearn import svm

svm_model = svm.SVC(decision_function_shape='ovr')
svm_model.fit(X_train, y_train)

#We predict the training set
predict_train = svm_model.predict(X_train)
#we predict the test set
predict_test = svm_model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')
#we report the confusion matrix for the training set
print(confusion_matrix(y_train,predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train,predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))



(386, 77)
(166, 77)
Training accuracy
[[35  0  0  0  0  0  0  0]
 [ 0 48  0  0  0  0  0  0]
 [ 0  0 40  0  0  0  0  0]
 [ 0  0  0 54  0  0  0  0]
 [ 2  0  0  0 60  0  0  0]
 [ 0  0  0  0  0 51  0  0]
 [ 0  0  3  0  0  0 39  0]
 [ 0  0  0  0  0  0  0 54]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        35
           1       1.00      1.00      1.00        48
           2       0.93      1.00      0.96        40
           3       1.00      1.00      1.00        54
           4       1.00      0.97      0.98        62
           5       1.00      1.00      1.00        51
           6       1.00      0.93      0.96        42
           7       1.00      1.00      1.00        54

    accuracy                           0.99       386
   macro avg       0.98      0.99      0.99       386
weighted avg       0.99      0.99      0.99       386

Testing accuracy
[[10  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0 

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [2]:
print(mice.details["id"])

40966
