In [ ]:



from sklearn.datasets import fetch_openml
#load mice protein dataset from OpenML
mice = fetch_openml(name='miceprotein', version=4, as_frame=True)
list(mice.frame.columns)
#print(mice.details)
#mice.frame.describe()


# Import required libraries
import numpy as np 
import sklearn
from sklearn.neural_network import MLPClassifier


# Import model to divide data into training and testing sets
from sklearn.model_selection import train_test_split


target_column = ['class'] 
#derive the list of predictor column id's
predictors = list(set(list(mice.frame.columns))-set(target_column))
#standardize the predictors by diividing by the maximum
mice.frame[predictors] = mice.frame[predictors]/mice.frame[predictors].max()
#provide summary statistics for the dataframe
mice.frame.describe().transpose()

#Get rid of any rown with NA's
mice.frame = mice.frame.dropna()

#the input data
X = mice.frame[predictors].values
#the output data
y = mice.frame[target_column].values

#we encode target classes from strings to numbers as neural networks cannot require all numerical inputs and outputs
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#divide data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train.shape); print(X_test.shape)

#impor the neural network (aka multi-layer-perceptron library)
from sklearn.neural_network import MLPClassifier

#The network architecture will consist of 1 input layer that has as many input nodes as columns-1, 3 hidden layers of 20 nodes each,
# and an output layer with a node for each of the categories--and the network will choose the one with the highest score
mlp = MLPClassifier(hidden_layer_sizes=(15,15,15), activation='relu', solver='adam', max_iter=2000)
#mlp = MLPClassifier(hidden_layer_sizes=(20,20,20), activation='relu', solver='adam', max_iter=5000)
#we train the network
mlp.fit(X_train,y_train)

#We predict the training set
predict_train = mlp.predict(X_train)
#we predict the test set
predict_test = mlp.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')
#we report the confusion matrix for the training set
print(confusion_matrix(y_train,predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train,predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))

#Now rerun but above change the network architecture to 
#mlp = MLPClassifier(hidden_layer_sizes=(20,20,20), activation='relu', solver='adam', max_iter=5000)


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(386, 77)
(166, 77)
Training accuracy
[[30  0  0  0  0  0  0  0]
 [ 0 63  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0]
 [ 0  0  0  0 61  1  0  0]
 [ 0  0  0  0  0 48  0  0]
 [ 0  0  0  0  0  0 39  0]
 [ 0  0  0  0  0  0  0 48]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        63
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        55
           4       1.00      0.98      0.99        62
           5       0.98      1.00      0.99        48
           6       1.00      1.00      1.00        39
           7       1.00      1.00      1.00        48

    accuracy                           1.00       386
   macro avg       1.00      1.00      1.00       386
weighted avg       1.00      1.00      1.00       386

Testing accuracy
[[14  0  0  0  0  0  0  1]
 [ 0 12  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0 